### ISSUE TITLE
solve_ilp_problem(unique=?)

### ISSUE THREAD

**Issue by bwang482** [boudinfl/sume#8]
Hi Florian,

Thanks for your great work! In concept_based.py - `solve_ilp_problem()` there is an argument:

`unique (bool): modify the model so that it produces only one optimal solution, defaults to False`

I am not sure I understand the use of this parameter, would you please enlighten me on this? Thanks!

**Comment by boudinfl** [comment]
Concept pruning in the original model of [(Gillick and Favre, 2009)](http://www.icsi.berkeley.edu/pubs/speech/scalablemodel09.pdf) can lead to multiple optimal subset of sentences/summaries (details about issue can be found in this [paper](http://aclweb.org/anthology/D15-1220.pdf)).

Setting the `unique` argument to `True` introduces a second term in the objective function that prevents multiple optimal solutions (but slows down the solving time). More details on that are in the Section 3.3 of the [paper](http://aclweb.org/anthology/D15-1220.pdf).

Best,

**Comment by bwang482** [comment]
Thanks for the quick reply.
